name: hackconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - freetype=2.12.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - libnsl=2.0.1
  - libpng=1.6.44
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.6.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
  - pip:
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - distro==1.9.0
      - fastapi==0.115.5
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - fsspec==2024.10.0
      - gradio==5.7.1
      - gradio-client==1.5.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.0
      - huggingface-hub==0.26.3
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.8.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - langchain-core==0.3.21
      - langchain-openai==0.2.10
      - langsmith==0.1.147
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.55.3
      - opencv-python==4.10.0.84
      - orjson==3.10.12
      - pandas==2.2.3
      - py-cpuinfo==9.0.0
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pyparsing==3.2.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - ruff==0.8.1
      - safehttpx==0.1.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.41.3
      - sympy==1.13.1
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tomlkit==0.12.0
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - typer==0.14.0
      - tzdata==2024.2
      - ultralytics==8.3.39
      - ultralytics-thop==2.0.12
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - websockets==12.0
